#Spawn Command
x: 78.0
y: 71.0
z: -115.0
pitch: -1.9
yaw: 93.5
world-name: world

#plugin_configs
rawgens:
  #If using Gradients please make sure the gradients are in the & sign color code
  plugin_message: "&7[&x&f&f&0&0&0&0R&x&e&e&0&0&0&0a&x&d&e&0&0&0&0w&x&c&d&0&0&0&0G&x&b&c&0&0&0&0e&x&a&c&0&0&0&0n&x&9&b&0&0&0&0s&7]>"
  discord: "https://discord.gg/45YR3M6W"